dir/b/s A:\*.* > "B:\Alpha Public Files.txt"
dir/b/s B:\*.* > "B:\Alpha Backup Files.txt"
dir/b/s P:\*.* > "B:\Charlie Files.txt"
dir/b/s G:\*.* > "B:\Delta Files.txt"
dir/b/s H:\*.* > "B:\Echo Files.txt"
dir/b/s K:\*.* > "B:\Foxtrot Files.txt"
dir/b/s Q:\*.* > "B:\Golf Files.txt"
dir/b/s \\GGGSCP1\C\*.* > "B:\GGGSCP1 C Files.txt"
dir/b/s \\GGGSCP1\D\*.* > "B:\GGGSCP1 D Files.txt"